//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:eppcom-1.0")
package ietf.params.xml.ns.eppcom_1;
