//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//


package ietf.params.xml.ns.epp_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dcpStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dcpStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purpose" type="{urn:ietf:params:xml:ns:epp-1.0}dcpPurposeType"/>
 *         &lt;element name="recipient" type="{urn:ietf:params:xml:ns:epp-1.0}dcpRecipientType"/>
 *         &lt;element name="retention" type="{urn:ietf:params:xml:ns:epp-1.0}dcpRetentionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dcpStatementType", propOrder = {
    "purpose",
    "recipient",
    "retention"
})
public class DcpStatementType {

    @XmlElement(required = true)
    protected DcpPurposeType purpose;
    @XmlElement(required = true)
    protected DcpRecipientType recipient;
    @XmlElement(required = true)
    protected DcpRetentionType retention;

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link DcpPurposeType }
     *     
     */
    public DcpPurposeType getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcpPurposeType }
     *     
     */
    public void setPurpose(DcpPurposeType value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link DcpRecipientType }
     *     
     */
    public DcpRecipientType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcpRecipientType }
     *     
     */
    public void setRecipient(DcpRecipientType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the retention property.
     * 
     * @return
     *     possible object is
     *     {@link DcpRetentionType }
     *     
     */
    public DcpRetentionType getRetention() {
        return retention;
    }

    /**
     * Sets the value of the retention property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcpRetentionType }
     *     
     */
    public void setRetention(DcpRetentionType value) {
        this.retention = value;
    }

}
