//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//


package ietf.params.xml.ns.epp_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dcpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dcpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="access" type="{urn:ietf:params:xml:ns:epp-1.0}dcpAccessType"/>
 *         &lt;element name="statement" type="{urn:ietf:params:xml:ns:epp-1.0}dcpStatementType" maxOccurs="unbounded"/>
 *         &lt;element name="expiry" type="{urn:ietf:params:xml:ns:epp-1.0}dcpExpiryType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dcpType", propOrder = {
    "access",
    "statement",
    "expiry"
})
public class DcpType {

    @XmlElement(required = true)
    protected DcpAccessType access;
    @XmlElement(required = true)
    protected List<DcpStatementType> statement;
    protected DcpExpiryType expiry;

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link DcpAccessType }
     *     
     */
    public DcpAccessType getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcpAccessType }
     *     
     */
    public void setAccess(DcpAccessType value) {
        this.access = value;
    }

    /**
     * Gets the value of the statement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcpStatementType }
     * 
     * 
     */
    public List<DcpStatementType> getStatement() {
        if (statement == null) {
            statement = new ArrayList<DcpStatementType>();
        }
        return this.statement;
    }

    /**
     * Gets the value of the expiry property.
     * 
     * @return
     *     possible object is
     *     {@link DcpExpiryType }
     *     
     */
    public DcpExpiryType getExpiry() {
        return expiry;
    }

    /**
     * Sets the value of the expiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link DcpExpiryType }
     *     
     */
    public void setExpiry(DcpExpiryType value) {
        this.expiry = value;
    }

}
