//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//

package ietf.params.xml.ns.epp_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for eppType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;eppType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;choice&gt;
 *         &lt;element name=&quot;greeting&quot; type=&quot;{urn:ietf:params:xml:ns:epp-1.0}greetingType&quot;/&gt;
 *         &lt;element name=&quot;hello&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;/&gt;
 *         &lt;element name=&quot;command&quot; type=&quot;{urn:ietf:params:xml:ns:epp-1.0}commandType&quot;/&gt;
 *         &lt;element name=&quot;response&quot; type=&quot;{urn:ietf:params:xml:ns:epp-1.0}responseType&quot;/&gt;
 *         &lt;element name=&quot;extension&quot; type=&quot;{urn:ietf:params:xml:ns:epp-1.0}extAnyType&quot;/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "epp", namespace = "urn:ietf:params:xml:ns:epp-1.0")
public class EppType {
	@XmlElement(name = "command")
	private Object login;

	public EppType() {
	};

	public EppType(Object command) {
		super();
		this.login = command;
	}
}
