//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//


package ietf.params.xml.ns.epp_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for loginSvcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loginSvcType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *         &lt;element name="svcExtension" type="{urn:ietf:params:xml:ns:epp-1.0}extURIType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginSvcType", propOrder = {
    "objURI",
    "svcExtension"
})
public class LoginSvcType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected List<String> objURI;
    protected ExtURIType svcExtension;

    /**
     * Gets the value of the objURI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objURI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getObjURI() {
        if (objURI == null) {
            objURI = new ArrayList<String>();
        }
        return this.objURI;
    }

    /**
     * Gets the value of the svcExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtURIType }
     *     
     */
    public ExtURIType getSvcExtension() {
        return svcExtension;
    }

    /**
     * Sets the value of the svcExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtURIType }
     *     
     */
    public void setSvcExtension(ExtURIType value) {
        this.svcExtension = value;
    }

}
