//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.05 at 09:06:24 AM MESZ 
//


package ietf.params.xml.ns.epp_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result" type="{urn:ietf:params:xml:ns:epp-1.0}resultType" maxOccurs="unbounded"/>
 *         &lt;element name="msgQ" type="{urn:ietf:params:xml:ns:epp-1.0}msgQType" minOccurs="0"/>
 *         &lt;element name="resData" type="{urn:ietf:params:xml:ns:epp-1.0}extAnyType" minOccurs="0"/>
 *         &lt;element name="extension" type="{urn:ietf:params:xml:ns:epp-1.0}extAnyType" minOccurs="0"/>
 *         &lt;element name="trID" type="{urn:ietf:params:xml:ns:epp-1.0}trIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseType", propOrder = {
    "result",
    "msgQ",
    "resData",
    "extension",
    "trID"
})
public class ResponseType {

    @XmlElement(required = true)
    protected List<ResultType> result;
    protected MsgQType msgQ;
    protected ExtAnyType resData;
    protected ExtAnyType extension;
    @XmlElement(required = true)
    protected TrIDType trID;

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultType }
     * 
     * 
     */
    public List<ResultType> getResult() {
        if (result == null) {
            result = new ArrayList<ResultType>();
        }
        return this.result;
    }

    /**
     * Gets the value of the msgQ property.
     * 
     * @return
     *     possible object is
     *     {@link MsgQType }
     *     
     */
    public MsgQType getMsgQ() {
        return msgQ;
    }

    /**
     * Sets the value of the msgQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgQType }
     *     
     */
    public void setMsgQ(MsgQType value) {
        this.msgQ = value;
    }

    /**
     * Gets the value of the resData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtAnyType }
     *     
     */
    public ExtAnyType getResData() {
        return resData;
    }

    /**
     * Sets the value of the resData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtAnyType }
     *     
     */
    public void setResData(ExtAnyType value) {
        this.resData = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtAnyType }
     *     
     */
    public ExtAnyType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtAnyType }
     *     
     */
    public void setExtension(ExtAnyType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the trID property.
     * 
     * @return
     *     possible object is
     *     {@link TrIDType }
     *     
     */
    public TrIDType getTrID() {
        return trID;
    }

    /**
     * Sets the value of the trID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrIDType }
     *     
     */
    public void setTrID(TrIDType value) {
        this.trID = value;
    }

}
